CoreBundle\Entity\Scan:
  type: entity
  table: scans
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    userId:
      name: user_id
      type: integer
    executedAt:
      name: executed_at
      type: datetime
  manyToOne:
    scanData:
      targetEntity: ScanData
      joinColumn:
        name: scan_data_id
        referencedColumnName: id
