CoreBundle\Entity\ScanData:
  type: entity
  table: scan_data
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    scanId:
      name: scan_id
      type: integer
    amount:
      type: integer

  manyToOne:
    currencyItem:
      targetEntity: CurrencyItem
      joinColumn:
        name: currency_item_id
        referencedColumnName: id
